volumes:
    postgres-data:
        external: true

services:
  postgres:
    build:
        context: ./relational-data
        dockerfile: ./Dockerfile.dev
    volumes:
        - postgres-data:/var/lib/postgresql/data
    environment:
        - POSTGRES_MULTIPLE_DATABASES=users
        - POSTGRES_PASSWORD=test-databases
    ports:
        - 15432:5432
  users-api:
    build:
      context: ./users-api-service
      dockerfile: ./Dockerfile.dev
    ports:
      - "8000:8000"
    volumes:
      - ./users-api-service:/app
    environment:
      DATABASE_URL: postgres://users:password@postgres:5432/users
      WAIT_HOSTS: postgres:5432
      WAIT_TIMEOUT: 240
    # depends_on:
    #   - usersdb

  ghi:
    image: node:lts-bullseye
    command: /bin/bash run.sh
    working_dir: /app
    volumes:
      - ./ghi:/app
    ports:
      - "3000:3000"
    environment:
      HOST_OS: ${OS}
      NODE_ENV: development
      HOST: "0.0.0.0"
      PUBLIC_URL: http://localhost:3000
      REACT_APP_USERS_SERVICE_API_HOST: http://localhost:8000
